name: 'Add a release for tags'
description: 'Add a release (with a compare link) for a tag if there is none'
inputs:
  debug:
    description: 'If you extra debugging information should be printed in the action console output'
    required: false
    default: false
  draft:
    description: 'If the releases should be a draft or not'
    required: false
    default: true
  repo-token:  # GitHub API Token
    description: 'The GitHub API token'
    required: true
    default: 'GHAPITOKEN'
outputs:
  time: # id of output
    description: 'The time the comment was added'
runs:
  using: 'node12'
  main: 'addRelease.js'
